export const lifeChapters = [
  { id: "NEW_BEGINNING", label: "New Beginning", th: "การเริ่มต้นใหม่", note: "A threshold, move, or fresh chapter" },
  { id: "GROWTH_SUCCESS", label: "Growth & Success", th: "การเติบโตและความสำเร็จ", note: "Patient progress and work taking shape" },
  { id: "HOME_FAMILY", label: "Home & Family", th: "บ้านและครอบครัว", note: "Belonging, care, and a place held close" },
  { id: "LOVE_CONNECTION", label: "Love & Connection", th: "ความรักและความผูกพัน", note: "A bond, partnership, or shared life" },
  { id: "INNER_STRENGTH", label: "Inner Strength", th: "พลังใจ", note: "Steadiness through challenge and change" },
] as const;

export const collections = [
  { id: "MOUNTAIN_MIST", label: "Mountain & Mist", th: "ดอยและสายหมอก", note: "Layered horizons, cool air, quiet distance", tone: "quiet-mountain" },
  { id: "SACRED_RIVER", label: "Sacred River", th: "สายน้ำแห่งความหมาย", note: "A poetic collection name, not a religious claim", tone: "sacred-river" },
  { id: "GOLDEN_LANNA", label: "Golden Lanna", th: "ล้านนาในแสงทอง", note: "Warm fields with restrained antique-gold light", tone: "golden-forest" },
  { id: "NORTHERN_GARDEN", label: "Northern Garden", th: "สวนเมืองเหนือ", note: "Observed leaves, flowers, and calm breathing room", tone: "new-dawn" },
] as const;

export const moods = [
  { id: "QUIET", label: "Quiet", th: "สงบนิ่ง", tone: "quiet-mountain" },
  { id: "WARM", label: "Warm", th: "อบอุ่น", tone: "golden-forest" },
  { id: "MAJESTIC", label: "Majestic", th: "สง่างาม", tone: "new-dawn" },
] as const;

export const galleryFilters = ["New Beginning", "Family", "Love", "Growth", "Inner Strength", "Chiang Mai Memories"] as const;
export type GalleryFilter = (typeof galleryFilters)[number];

export const artworks = [
  { id: "first-light", title: "FIRST LIGHT", chapter: "New Beginning", filter: "New Beginning", collection: "Mountain & Mist", mood: "Quiet", tone: "new-dawn", shortStory: "A new path opens without asking the old roots to disappear.", story: "This study holds the feeling of beginning again while keeping a steady connection to what came before.", artDirection: "A low mountain horizon opens into pale morning air. One rooted tree anchors the near field while a narrow current guides the eye forward.", hero: "Rooted garden tree", support: ["Layered mountain ridge", "Narrow stream", "Morning mist"], palette: "Mist jade, aged paper, charcoal, restrained antique gold", composition: "Low horizon, left anchor, open upper-right field", archetype: "Open Horizon", symbolism: "A personal image of beginning with steadiness", observation: "The open upper-right field gives the destination quiet visual space.", createdDate: "29 August 2026", commissionNumber: "ML-DEMO-001", edition: "Demonstration study 1/1" },
  { id: "held-close", title: "HELD CLOSE", chapter: "Home & Family", filter: "Family", collection: "Northern Garden", mood: "Warm", tone: "guardian", shortStory: "A garden gathers around the quiet center of home.", story: "An imagined family garden becomes a visual place of return, built from ordinary botanical forms rather than a claimed traditional symbol.", artDirection: "A sheltered garden tree sits at the center, with broad leaves and small blossoms forming a calm perimeter.", hero: "Sheltering garden tree", support: ["Broad leaves", "Jasmine sprigs", "Earthen vessel"], palette: "Botanical ivory, leaf jade, earthen vermillion", composition: "Centered shelter with a quiet perimeter", archetype: "Sheltered Garden", symbolism: "Personal symbolism for care and belonging", observation: "Botanical forms gather around the center while leaving the upper field quiet.", createdDate: "29 August 2026", commissionNumber: "ML-DEMO-002", edition: "Demonstration study 1/1" },
  { id: "the-current-between-us", title: "THE CURRENT BETWEEN US", chapter: "Love & Connection", filter: "Love", collection: "Sacred River", mood: "Warm", tone: "sacred-river", shortStory: "Two banks remain connected by the movement between them.", story: "The river is used as an artistic metaphor for connection and continuity. No sacred or historical meaning is asserted.", artDirection: "A winding current leads between two planted banks, joining near and distant space through one continuous line.", hero: "Winding river", support: ["River stones", "Two planted banks", "Distant hills"], palette: "River blue, deep jade, warm ivory", composition: "Flowing diagonal with paired banks", archetype: "Flowing Connection", symbolism: "A personal image of connection across distance", observation: "The river carries the eye between paired banks toward wider space.", createdDate: "29 August 2026", commissionNumber: "ML-DEMO-003", edition: "Demonstration study 1/1" },
  { id: "patient-gold", title: "PATIENT GOLD", chapter: "Growth & Success", filter: "Growth", collection: "Golden Lanna", mood: "Majestic", tone: "golden-forest", shortStory: "Light gathers gradually where the long work is headed.", story: "Repeated field forms create a measured rhythm of progress, with warmth increasing toward the destination.", artDirection: "Cultivated botanical forms rise in stages. Gold remains restrained and concentrates only near the far opening.", hero: "Sunlit botanical canopy", support: ["Rice stems", "Cultivated field rhythm", "Distant ridge"], palette: "Rice gold, muted vermillion, charcoal", composition: "Measured ascent toward a warm destination", archetype: "Rising Field", symbolism: "Personal symbolism for patient growth", observation: "Gold is concentrated near the destination, creating increasing visual warmth.", createdDate: "29 August 2026", commissionNumber: "ML-DEMO-004", edition: "Demonstration study 1/1" },
  { id: "quiet-ridge", title: "QUIET RIDGE", chapter: "Inner Strength", filter: "Inner Strength", collection: "Mountain & Mist", mood: "Majestic", tone: "quiet-mountain", shortStory: "A strong horizon holds its place without becoming loud.", story: "The composition treats strength as steadiness: a clear ridge, ample air, and supporting forms that never compete with the hero.", artDirection: "A single mountain ridge holds the upper field while quiet layers settle below it.", hero: "Mountain ridge", support: ["Valley mist", "Teak leaves", "Open sky"], palette: "Deep jade, mist blue, charcoal", composition: "Upper ridge with broad calm lower layers", archetype: "Steadfast Ridge", symbolism: "A personal image of calm resilience", observation: "The broad calm layers keep the ridge visually steady without adding decorative weight.", createdDate: "29 August 2026", commissionNumber: "ML-DEMO-005", edition: "Demonstration study 1/1" },
  { id: "chiang-mai-evening", title: "CHIANG MAI EVENING", chapter: "Home & Family", filter: "Chiang Mai Memories", collection: "Golden Lanna", mood: "Warm", tone: "journey", shortStory: "Evening light keeps a remembered northern journey close.", story: "A contemporary landscape study shaped by an ordinary memory of Chiang Mai evening light. It makes no historical or sacred claim.", artDirection: "A path moves through cultivated edges toward warm evening air, with the city memory suggested through light and distance rather than landmarks.", hero: "Open evening path", support: ["Cultivated edges", "Distant mountains", "Warm sky"], palette: "Aged paper, muted vermillion, restrained antique gold", composition: "Forward path with a clear destination", archetype: "Remembered Journey", symbolism: "Personal symbolism for a place kept in memory", observation: "Warm light gathers along the path while distant mountains remain understated.", createdDate: "29 August 2026", commissionNumber: "ML-DEMO-006", edition: "Demonstration study 1/1" },
] as const;

export type ArtworkRecord = (typeof artworks)[number];

export const faqs = [
  ["What is an Art Direction?", "A free visual plan for your story art: chapter, collection, mood, narrative, hero, supporting elements, palette, composition, and interpretation boundaries."],
  ["Do I need to share a personal story?", "No. The story is optional and limited to one to five sentences. Your selected chapter, collection, and mood are enough to begin."],
  ["Will there be writing or sacred symbols in the artwork?", "No. Artwork prompts exclude text, Thai/Lanna/Pali pseudo-writing, yantras, sacred text, signatures, logos, and watermarks."],
  ["Are the prices final?", "No. All displayed ranges are editable P0 test ranges, not a fixed price or commercial quote."],
] as const;
