import Link from "next/link";
import { ArtworkComposition } from "./artwork-composition";
import { artworks } from "@/content/mock-data";
import { formatTestRange, PACKAGE_CONFIG } from "@/config/packages";

export function ArtworkGrid({ limit = artworks.length }: { limit?: number }) { return <div className="art-grid">{artworks.slice(0, limit).map((art, i) => <Link href={`/artwork/${art.id}`} className={`art-tile art-tile--${(i % 3) + 1}`} key={art.id}><ArtworkComposition tone={art.tone} compact title={art.title}/><div><small>DEMONSTRATION · {String(i + 1).padStart(2, "0")}</small><h3>{art.title}</h3><p>{art.chapter} · {art.collection}</p><p className="art-tile__meaning">{art.shortStory}</p></div></Link>)}</div>; }

export function PackageList({ compact = false }: { compact?: boolean }) { return <div className={`package-list ${compact ? "package-list--compact" : ""}`}>{PACKAGE_CONFIG.map((item) => <article className="package-row" key={item.id}><header><span>0{PACKAGE_CONFIG.indexOf(item) + 1}</span><div><h3>{item.name}</h3><p>{formatTestRange(item.range)} <small>editable test range</small></p></div></header><ul>{item.deliverables.map((deliverable) => <li key={deliverable}>{deliverable}</li>)}</ul><p className="package-entitlement">{item.artDirectionAdjustments === 1 ? "Exactly one Art Direction Adjustment" : "Art Direction review included"}</p></article>)}</div>; }

export function CulturalNote() { return <aside className="cultural-note"><span className="ornament" aria-hidden="true">✦</span><div><p className="eyebrow">OUR CULTURAL APPROACH</p><h2>Clear about reference,<br/>interpretation, and meaning</h2><div className="cultural-labels"><strong>Cultural Reference</strong><strong>Artistic Interpretation</strong><strong>Personal Symbolism</strong></div><p>We separate observed Northern Thai and Lanna visual references from contemporary artistic choices and the meaning a customer brings. We do not invent sacred, religious, historical, or supernatural claims.</p><Link href="/cultural-approach" className="text-link">Read our cultural approach <span>↗</span></Link></div></aside>; }
