import type { SymbolRecord } from "../types";

const worlds = ["mountain-dawn", "teak-courtyard", "rice-terraces", "forest-stream", "botanical-atelier", "earthen-village", "mist-valley", "northern-garden"];
const base = { version: "1.0.0", region: "THAI_LANNA" as const, status: "PUBLISHED" as const, active: true, confidence: "DECORATIVE" as const, spiritualMin: "CULTURAL" as const, spiritualMax: "SYMBOLIC" as const, conflictsWith: [] as string[] };

export const SYMBOL_SEEDS: readonly SymbolRecord[] = Object.freeze([
  { ...base, id: "mountain-ridge", name: "Mountain ridge", category: "LANDSCAPE", visualDescription: "Layered northern mountain silhouettes receding through mist.", culturalNote: null, artisticInterpretation: "An artistic image of steadiness and a long view; not a historical claim.", promptFragment: "layered northern Thai mountain ridges in quiet atmospheric depth", compatibleWorldIds: worlds, allowedAsHero: true },
  { ...base, id: "winding-stream", name: "Winding stream", category: "LANDSCAPE", visualDescription: "A narrow stream making a gentle path through the scene.", culturalNote: null, artisticInterpretation: "An artistic image of continuity and change; not a cultural meaning.", promptFragment: "a gently winding stream guiding the eye through the scene", compatibleWorldIds: ["forest-stream", "rice-terraces", "mist-valley", "northern-garden"], allowedAsHero: true },
  { ...base, id: "rice-stems", name: "Rice stems", category: "BOTANICAL", visualDescription: "Observed rice stems grouped as a cultivated field detail.", culturalNote: "Rice cultivation is part of ordinary agricultural landscape in northern Thailand; no ritual meaning is asserted.", artisticInterpretation: "Used artistically as a patient rhythm of growth.", promptFragment: "observed rice stems arranged as a restrained field rhythm", compatibleWorldIds: ["rice-terraces", "earthen-village", "northern-garden"], allowedAsHero: true },
  { ...base, id: "banana-leaves", name: "Banana leaves", category: "BOTANICAL", visualDescription: "Broad banana leaves with visible veins and natural bends.", culturalNote: null, artisticInterpretation: "Decorative sheltering forms with no claimed symbolic tradition.", promptFragment: "broad banana leaves with observed veins and natural bends", compatibleWorldIds: ["forest-stream", "botanical-atelier", "earthen-village", "northern-garden"], allowedAsHero: true },
  { ...base, id: "jasmine-sprigs", name: "Jasmine sprigs", category: "BOTANICAL", visualDescription: "Small white jasmine blossoms and green sprigs used decoratively.", culturalNote: null, artisticInterpretation: "A quiet light accent, without assigning a factual cultural meaning.", promptFragment: "small white jasmine blossoms as sparse botanical accents", compatibleWorldIds: ["teak-courtyard", "botanical-atelier", "northern-garden"], allowedAsHero: false },
  { ...base, id: "teak-leaves", name: "Teak leaves", category: "BOTANICAL", visualDescription: "Large matte leaves rendered from direct botanical form.", culturalNote: null, artisticInterpretation: "A broad grounding shape used as contemporary botanical material.", promptFragment: "large matte teak leaves with restrained hand-painted contour", compatibleWorldIds: ["mountain-dawn", "teak-courtyard", "forest-stream", "botanical-atelier", "earthen-village", "mist-valley"], allowedAsHero: true },
  { ...base, id: "clay-vessel", name: "Clay vessel", category: "OBJECT", visualDescription: "An undecorated everyday earthenware vessel.", culturalNote: "Presented only as an ordinary material object; no ceremonial provenance or meaning is claimed.", artisticInterpretation: "A simple vessel shape suggesting held space as personal symbolism.", promptFragment: "an undecorated everyday earthenware vessel with a quiet silhouette", compatibleWorldIds: ["teak-courtyard", "botanical-atelier", "earthen-village", "northern-garden"], allowedAsHero: true },
  { ...base, id: "woven-cotton", name: "Woven cotton", category: "MATERIAL", visualDescription: "Plain handwoven cotton represented through soft bands and fibers.", culturalNote: "Described as material appearance only; no pattern, community attribution or ceremonial use is claimed.", artisticInterpretation: "Soft linear rhythm used to convey connection as personal symbolism.", promptFragment: "plain woven cotton fibers forming soft unmarked bands", compatibleWorldIds: ["teak-courtyard", "botanical-atelier", "earthen-village"], allowedAsHero: false },
  { ...base, id: "timber-window", name: "Timber window", category: "ARCHITECTURE", visualDescription: "A simple secular timber opening without temple or ceremonial details.", culturalNote: "A non-ceremonial domestic spatial detail; no date, provenance or sacred context is asserted.", artisticInterpretation: "A framing device for openness and attention as personal symbolism.", promptFragment: "a simple northern Thai domestic timber opening without ceremonial detail", compatibleWorldIds: ["teak-courtyard", "earthen-village"], allowedAsHero: true },
  { ...base, id: "small-clouds", name: "Small clouds", category: "LANDSCAPE", visualDescription: "Soft natural cloud forms used in the distant atmosphere.", culturalNote: null, artisticInterpretation: "Decorative movement and breathing room without supernatural meaning.", promptFragment: "small natural cloud forms drifting through distant mist", compatibleWorldIds: worlds, allowedAsHero: false },
  { ...base, id: "naga-figure", name: "Naga figure", category: "MYTHOLOGICAL", visualDescription: "A culturally specific mythological figure pending Thai/Lanna expert review.", culturalNote: "No meaning or permitted context is published until human cultural review is complete.", artisticInterpretation: "No automatic artistic interpretation is authorized.", promptFragment: "curator-blocked mythological figure", compatibleWorldIds: worlds, allowedAsHero: false, status: "REVIEW_REQUIRED", active: false, confidence: "INSPIRED", spiritualMin: "SYMBOLIC", spiritualMax: "SYMBOLIC", culturalReview: { status: "PENDING" } },
  { ...base, id: "sacred-hall", name: "Sacred hall", category: "ARCHITECTURE", visualDescription: "Sacred-adjacent architecture held for expert review and manual workflow only.", culturalNote: "No factual description or use permission is asserted in P0.", artisticInterpretation: "No automatic artistic interpretation is authorized.", promptFragment: "curator-blocked sacred architecture", compatibleWorldIds: worlds, allowedAsHero: false, status: "REVIEW_REQUIRED", active: false, confidence: "INSPIRED", spiritualMin: "SACRED", spiritualMax: "SACRED", culturalReview: { status: "PENDING" } },
]);
