import type { ArtWorld } from "../types";
const base={version:"1.0.0",region:"THAI_LANNA" as const,status:"PUBLISHED" as const,active:true,negativeConstraints:["no religious figures, ceremonial objects, writing, or non-Thai architecture"]};
const make=(id:string,name:string,visualDna:string[],environmentFragments:string[],compatibleSymbolIds:string[],paletteIds:string[],compositionIds:string[]):ArtWorld=>({...base,id,name,visualDna,environmentFragments,compatibleSymbolIds,paletteIds,compositionIds});
export const WORLD_SEEDS: readonly ArtWorld[]=Object.freeze([
 make("mountain-dawn","Mountain Dawn",["contemporary northern Thai mural restraint","layered hand-painted line and mineral-like wash"],["northern Thai mountain air at first light"],["mountain-ridge","teak-leaves","small-clouds"],["dawn-lacquer","mist-jade"],["low-horizon","upper-ridge","layered-field"]),
 make("teak-courtyard","Teak Courtyard",["quiet secular northern Thai domestic space","matte timber geometry with restrained botanical edges"],["an ordinary shaded timber courtyard without ceremonial detail"],["teak-leaves","jasmine-sprigs","clay-vessel","woven-cotton","timber-window","small-clouds"],["indigo-timber","earthen-vermillion"],["central-sanctum","garden-orbit"]),
 make("rice-terraces","Rice Terraces",["observed northern Thai cultivated landscape","rhythmic field contours with quiet mural depth"],["terraced rice landscape below distant hills"],["mountain-ridge","winding-stream","rice-stems","small-clouds"],["rice-gold","mist-jade"],["low-horizon","diagonal-ascent","layered-field"]),
 make("forest-stream","Forest Stream",["humid northern Thai forest atmosphere","organic hand-painted contours and translucent depth"],["a shaded stream among broad leaves and natural stones"],["mountain-ridge","winding-stream","banana-leaves","teak-leaves","small-clouds"],["forest-rain","mist-jade"],["left-anchor","diagonal-ascent"]),
 make("botanical-atelier","Botanical Atelier",["contemporary Thai botanical study","spacious ivory field and observed plant silhouettes"],["a quiet studio-like botanical arrangement without writing"],["banana-leaves","jasmine-sprigs","teak-leaves","clay-vessel","woven-cotton"],["botanical-ivory","earthen-vermillion"],["central-sanctum","garden-orbit"]),
 make("earthen-village","Earthen Village",["secular northern Thai village material palette","simple domestic forms and cultivated edges"],["ordinary earthen paths and timber dwellings without sacred architecture"],["mountain-ridge","rice-stems","banana-leaves","teak-leaves","clay-vessel","woven-cotton","timber-window","small-clouds"],["earthen-vermillion","indigo-timber"],["central-sanctum","layered-field"]),
 make("mist-valley","Mist Valley",["spacious northern Thai valley atmosphere","soft layered silhouettes with disciplined negative space"],["a mist-filled valley between distant mountain forms"],["mountain-ridge","winding-stream","teak-leaves","small-clouds"],["mist-jade","dawn-lacquer"],["right-threshold","upper-ridge","low-horizon"]),
 make("northern-garden","Northern Garden",["contemporary northern Thai garden calm","observed foliage grouped in balanced mural rhythm"],["an ordinary garden edge with water and cultivated plants"],["winding-stream","rice-stems","banana-leaves","jasmine-sprigs","clay-vessel","small-clouds"],["botanical-ivory","rice-gold"],["garden-orbit","central-sanctum"]),
]);
